### ISSUE TITLE
Unable to load widget locally

### ISSUE THREAD

**Issue by nvzoll** [click-connector/clickconnector-widget-sdk#1]
Steps to reproduce:
1. Add the widget to project running on local server

Expected result:
- Widget loads

Actual result:
- Widget does not load
- `GET http://localhost:7567/api/v1/widgets/9a0480-ffb87/public net::ERR_CONNECTION_REFUSED` in console
- Text search over widget.js finds this chunk: 
```
const r="PROD"==(-1<window.location.hostname.indexOf("localhost")||-1<window.location.hostname.indexOf("192.168")?"LOCAL":"PROD")?{env:"PROD",ENGINE_BASE_PATH:"https://engine.clickconnector.app/api/v1"}:{env:"LOCAL",ENGINE_BASE_PATH:"http://localhost:7567/api/v1"}}
```

Notes:
- Makes no sense for code end users

**Comment by click-connector** [comment]
Resolved

**Comment by nvzoll** [comment]
@click-connector @Ragularuban sorry to report, I still can't see the widget locally. Now there are no errors in console, and I see widget's messages in there, and widget script element in DOM, but there is no widget container. Additionally, now we have an issue with user conversation with bot getting overwritten when next user starts messaging, like there could be only one conversation in the system.

**Comment by Ragularuban** [comment]
@nvzoll I just checked the testing on my local, and it seems to be working. I'll try to reproduce this again in a while.

I'm a little confused about your message - "user conversation with bot getting overwritten when next user starts messaging"

Is the user trying to start a new conversation while having an existing conversation with the bot?

Multi-Chats - In the chat widget settings, under power settings, there is an option to enable multiple chats "Allow Multiple Active Chats"

**Comment by click-connector** [comment]
Re-opening for testing

**Comment by Ragularuban** [comment]
@nvzoll I just tested again on localhost and it seems to be working.

1) Install React/NextJS - `npx create-next-app@latest`
2) Add the snippet for widget loading
```
import { ChatWidget } from "@clickconnector/widget-sdk";

// Load the widget
ChatWidget.load("xxxxx-xxxxxx").then(() => {
  console.log("Widget loaded");
});
```

3) And the widget loads...
<img width="1405" alt="Screenshot 2024-12-18 at 00 14 40" src="https://github.com/user-attachments/assets/03a6502a-c63c-4133-88d1-7d20cd3b32b9" />

--------------

Please cross-check if you have added any other restrictions in your widget settings 
- Country Restriction
- IP restriction
- Domain Restriction

**Comment by nvzoll** [comment]
@Ragularuban thanks for noticing.
The problem I tried to describe is not there anymore, but this is how it looked:
1. Login to project with chat installed
2. Click 'Start conversation', don't post anything
3. Open an Incognito mode browser window
4. Login to project from different account, start chatting
5. User from (1) sees messages from user from step (4)
6. If user (1) inputs a message, in goes into same inbox and contact name/email gets overwritten.

**Comment by nvzoll** [comment]
And yes, I simply forgot to put localhost to domain list. Please update installation instructions, because it's really easy to miss. Issue is resolved. Thank you very much.

**Comment by click-connector** [comment]
From the description you have made - it looks like you might use the
identify API with the same id (both on browser and incognito)

That's the usual case for email to get overitten.

**Comment by nvzoll** [comment]
Yes, that was my first theory. But I double checked the code, and it uses user ids from our system and makes sure they are not undefined or something. (Would be easier to debug this if I could see those ids inside Click Connector dashboard).
But anyway, all is working now.

**Comment by nvzoll** [comment]
P.S. Actually, I had phoneNumbers undefined. That might be the source of problem.
